CREATE DATABASE sociofuracao DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE sociofuracao;


CREATE TABLE IF NOT EXISTS TIPOUSUARIO(
  IDTIPOSOCIO INTEGER PRIMARY KEY auto_increment,
  DESCRICAO VARCHAR(30) NOT NULL
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS PAIS(
  SIGLA VARCHAR(2) PRIMARY KEY,
  NOME VARCHAR(40) NOT null
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


CREATE TABLE IF NOT EXISTS ESTADO(
  SIGLA VARCHAR(2) PRIMARY KEY,
  NOME VARCHAR(40) NOT NULL,
  PAIS_SIGLA VARCHAR(2)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE ESTADO ADD CONSTRAINT ESTADO_FKINDEX1 FOREIGN KEY ESTADO(PAIS_SIGLA) REFERENCES PAIS(SIGLA);

CREATE TABLE IF NOT EXISTS CIDADE(
  NOME VARCHAR(40) PRIMARY KEY,
  ESTADO_SIGLA VARCHAR(2) NOT null
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE CIDADE ADD CONSTRAINT CIDADE_FKINDEX1 FOREIGN KEY CIDADE(ESTADO_SIGLA) REFERENCES ESTADO(SIGLA);

CREATE TABLE IF NOT EXISTS USUARIO(
  EMAIL VARCHAR(255) PRIMARY KEY,
  SENHA VARCHAR(100) NOT NULL,
  CPF VARCHAR(20) NOT NULL,
  RG VARCHAR(20) NOT NULL,
  ESTADO VARCHAR(2) NOT NULL,
  CIDADE_NOME VARCHAR(40) NOT NULL,
  PAIS VARCHAR(2) NOT NULL,
  TIPOSOCIO INTEGER NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  SEXO VARCHAR(10),
  DATANASCIMENTO DATE,
  ENDERECO VARCHAR(60),
  NUMERO VARCHAR(6),
  CEP VARCHAR(10),
  COMPLEMENTO VARCHAR(20),
  BAIRRO VARCHAR(30),
  FACEBOOK VARCHAR(255),
  TWITTER VARCHAR(255),
  INSTAGRAN VARCHAR(255),
  TELEFONE VARCHAR(20),
  CELULAR VARCHAR(20),
  ULTIMOACESSO DATETIME,
  DATACADASTRO DATETIME,
  DATAACESSO DATETIME
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FKINDEX1 FOREIGN KEY USUARIO(CIDADE_NOME) REFERENCES CIDADE(NOME);
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_FKINDEX2 FOREIGN KEY USUARIO(TIPOSOCIO) REFERENCES TIPOUSUARIO(IDTIPOSOCIO);

CREATE TABLE IF NOT exists CLUBE(
	CNPJ VARCHAR(20) PRIMARY KEY NOT NULL,
	CIDADE_NOME VARCHAR(40) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	ESCUDO BLOB,
	ENDERECO VARCHAR(60),
    NUMERO VARCHAR(20),
    COMPLEMENTO VARCHAR(30),
    BAIRRO VARCHAR(40),
    TELEFONE VARCHAR(20),
    FACEBOOK VARCHAR(255),
    TWITTER VARCHAR(255),
    INSTAGRAN VARCHAR(255)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE USUARIO ADD CONSTRAINT CLUBE_FKINDEX1 FOREIGN KEY CLUBE(CIDADE_NOME) REFERENCES CIDADE(NOME);

CREATE TABLE IF NOT EXISTS ESTADIO(
  ID INTEGER PRIMARY KEY  auto_increment,
  NOME VARCHAR(60) NOT NULL,
  NOMEFANTASIA VARCHAR(60),
  IMG BLOB,
  ENDERECO VARCHAR(60),
  NUMERO VARCHAR(20),
  COMPLEMENTO VARCHAR(30),
  BAIRRO VARCHAR(40),
  CAPACIDADE INTEGER NOT NULL,
  ADMINISTRADOR VARCHAR(40),
  TELEFONE VARCHAR(20)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS CLUBE_ESTADIO(
  CNPJ_CLUBE VARCHAR(20) NOT NULL,
  ID_ESTADIO INTEGER NOT NULL
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE CLUBE_ESTADIO ADD CONSTRAINT CLUBE_ESTADIO_FKINDEX1 FOREIGN KEY CLUBE_ESTADIO(CNPJ_CLUBE) REFERENCES CLUBE(CNPJ);
ALTER TABLE CLUBE_ESTADIO ADD CONSTRAINT CLUBE_ESTADIO_FKINDEX2 FOREIGN KEY CLUBE_ESTADIO(ID_ESTADIO) REFERENCES ESTADIO(ID);

CREATE TABLE IF NOT EXISTS SETOR(
  ID INTEGER PRIMARY KEY auto_increment,
  ESTADIO_ID INTEGER NOT NULL,
  DESCRICAO VARCHAR(60),
  VALORMINIMO DOUBLE,
  VALORMAXIMO DOUBLE,
  CAPACIDADE INTEGER
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE SETOR ADD CONSTRAINT SETOR_FKINDEX1 FOREIGN KEY SETOR(ESTADIO_ID) REFERENCES ESTADIO(ID);

CREATE TABLE IF NOT EXISTS LUGAR(
	ID INTEGER PRIMARY KEY auto_increment,
	USUARIO_EMAIL VARCHAR(255) NOT NULL,
	SETOR_ID INTEGER NOT NULL,
	FILEIRA INTEGER NOT NULL,
	NUMERO INTEGER NOT NULL,
	OBSERVACAO VARCHAR(255)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE LUGAR ADD CONSTRAINT LUGAR_FKINDEX1 FOREIGN KEY LUGAR(USUARIO_EMAIL) REFERENCES USUARIO(EMAIL);
ALTER TABLE LUGAR ADD CONSTRAINT LUGAR_FKINDEX2 FOREIGN KEY LUGAR(SETOR_ID) REFERENCES SETOR(ID);

ALTER TABLE LUGAR ADD CONSTRAINT UC_LUGAR UNIQUE (USUARIO_EMAIL,SETOR_ID,FILEIRA,NUMERO);

CREATE TABLE IF NOT EXISTS EVENTO(
  ID INTEGER PRIMARY KEY auto_increment,
  DATA DATE,
  HORA TIME,
  IMAGEM BLOB,
  ESTADIO_ID INTEGER NOT NULL,
  RESPONSAVEL VARCHAR(60),
  TIPOEVENTO VARCHAR(50),
  DESCRICAO VARCHAR(100)
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE EVENTO ADD CONSTRAINT EVENTO_FKINDEX1 FOREIGN KEY EVENTO(ESTADIO_ID) REFERENCES ESTADIO(ID);

CREATE TABLE IF NOT EXISTS TRANSACAO(
	ID INTEGER PRIMARY KEY auto_increment,
	USUARIO_EMAIL VARCHAR(255) NOT NULL,
	DATATRANS DATETIME,
	VALOR DOUBLE,
	FORMAPAGTO INTEGER
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

ALTER TABLE TRANSACAO ADD CONSTRAINT TRANSACAO_FKINDEX1 FOREIGN KEY TRANSACAO(USUARIO_EMAIL) REFERENCES USUARIO(EMAIL);


CREATE TABLE IF NOT EXISTS LUGAR_EVENTO(
    `LUGAR_ID` INTEGER NOT NULL,
	`EVENTO_ID` INTEGER NOT NULL,
	PRIMARY KEY(`LUGAR_ID`,`EVENTO_ID`),
	INDEX `fk_lugar/evento_id_idx` (`EVENTO_ID` ASC) ,
  CONSTRAINT `fk_lugar/lugar_fk`
    FOREIGN KEY (`lugar_id` )
    REFERENCES `sociofuracao`.`lugar` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lugar/evento_fk`
    FOREIGN KEY (`evento_id` )
    REFERENCES `sociofuracao`.`evento` (`id` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;


INSERT INTO PAIS(SIGLA,NOME) VALUES('BR', 'BRASIL');

INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('RO', 'RONDÔNIA', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('AC', 'ACRE', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('AM', 'AMAZONAS', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('RR', 'RORAIMA', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('PA', 'PARÁ', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('AP', 'AMAPÁ', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('TO', 'TOCANTINS', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('MA', 'MARANHÃO', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('PI', 'PIAUÍ', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('CE', 'CEARÁ', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('RN', 'RIO GRANDE DO NORTE', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('PB', 'PARAÍBA', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('PE', 'PERNAMBUCO', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('AL', 'ALAGOAS', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('SE', 'SERGIPE', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('BA', 'BAHIA', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('MG', 'MINAS GERAIS', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('ES', 'ESPIRITO SANTO', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('RJ', 'RIO DE JANEIRO', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('SP', 'SÃO PAULO', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('PR', 'PARANÁ', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('SC', 'SANTA CATARINA', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('RS', 'RIO GRANDE DO SUL', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('MS', 'MATO GROSSO DO SUL', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('MT', 'MATO GROSSO', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('GO', 'GOIÁS', 'BR');
INSERT INTO ESTADO(SIGLA, NOME, PAIS_SIGLA) VALUES('DF', 'DISTRITO FEDERAL', 'BR');

INSERT INTO CIDADE(NOME, ESTADO_SIGLA) VALUES('CURITIBA', 'PR');
INSERT INTO CIDADE(NOME, ESTADO_SIGLA) VALUES('SÃO PAULO', 'SP');

INSERT INTO TIPOUSUARIO(DESCRICAO) VALUES('SOCIO');
INSERT INTO TIPOUSUARIO(DESCRICAO) VALUES('NAO SOCIO');
INSERT INTO TIPOUSUARIO(DESCRICAO) VALUES('ADMINISTRADOR');

INSERT INTO USUARIO(EMAIL, SENHA, CPF, RG, CIDADE_NOME, ESTADO, PAIS, TIPOSOCIO, NOME, SEXO, DATANASCIMENTO,CELULAR) 
   VALUES('marcelo.rogerio@all-logistica.com', 'teste123', '003.702.429-98', '43434343', 'CURITIBA', 'PR', 'BR', 3, 'MARCELO ROGERIO DA SILVA', 'MASCULINO', '1978-10-01','99999999');
   

INSERT INTO CLUBE(CNPJ,CIDADE_NOME,NOME,ENDERECO,NUMERO,BAIRRO,TELEFONE)
  VALUES('78.425.986/0036-15','CURITIBA','CLUBE ATLÉTICO PARANENSE','RUA TESTE TESTE','1222','CENTRO','2131-1111');
  
INSERT INTO `sociofuracao`.`estadio`(`NOME`,`NOMEFANTASIA`,`ENDERECO`,`NUMERO`,`COMPLEMENTO`,`BAIRRO`,`CAPACIDADE`,`ADMINISTRADOR`,
`TELEFONE`) VALUES('ESTADIO ARENA DA BAIXADA','ESTADIO ARENA DA BAIXADA','RUA VEREADOR','1211','100','CENTOR',40000,'MARCELO ROGERIO',
'9999-9999');

INSERT INTO CLUBE_ESTADIO(CNPJ_CLUBE,ID_ESTADIO) VALUES('78.425.986/0036-15','1');

INSERT INTO setor(ESTADIO_ID,DESCRICAO,VALORMINIMO,VALORMAXIMO,CAPACIDADE)
	VALUES ('1','SETOR A001',45.00,60.00,5000);
INSERT INTO setor(ESTADIO_ID,DESCRICAO,VALORMINIMO,VALORMAXIMO,CAPACIDADE)
	VALUES ('1','SETOR B001',95.00,100.00,1000);
INSERT INTO setor(ESTADIO_ID,DESCRICAO,VALORMINIMO,VALORMAXIMO,CAPACIDADE)
	VALUES ('1','SETOR C001',98.00,120.00,4000);
INSERT INTO setor(ESTADIO_ID,DESCRICAO,VALORMINIMO,VALORMAXIMO,CAPACIDADE)
	VALUES ('1','SETOR D001',45.00,60.00,1000);
INSERT INTO setor(ESTADIO_ID,DESCRICAO,VALORMINIMO,VALORMAXIMO,CAPACIDADE)
	VALUES ('1','SETOR E001',45.00,60.00,3000);
INSERT INTO setor(ESTADIO_ID,DESCRICAO,VALORMINIMO,VALORMAXIMO,CAPACIDADE)
	VALUES ('1','SETOR F001',145.00,160.00,6000);
INSERT INTO setor(ESTADIO_ID,DESCRICAO,VALORMINIMO,VALORMAXIMO,CAPACIDADE)
	VALUES ('1','SETOR G001',175.00,200.00,15000);
INSERT INTO setor(ESTADIO_ID,DESCRICAO,VALORMINIMO,VALORMAXIMO,CAPACIDADE)
	VALUES ('1','SETOR T001',220.00,300.00,5000);
	
INSERT INTO LUGAR(USUARIO_EMAIL,SETOR_ID,FILEIRA,NUMERO,OBSERVACAO)
	VALUES('marcelo.rogerio@all-logistica.com', 1,1,100,'SETOR A001-1-100');

INSERT INTO LUGAR(USUARIO_EMAIL,SETOR_ID,FILEIRA,NUMERO,OBSERVACAO)
	VALUES('marcelo.rogerio@all-logistica.com', 1,1,200,'SETOR A001-1-200');

INSERT INTO LUGAR(USUARIO_EMAIL,SETOR_ID,FILEIRA,NUMERO,OBSERVACAO)
	VALUES('marcelo.rogerio@all-logistica.com', 1,10,100,'SETOR A001-10-100');


INSERT INTO LUGAR(USUARIO_EMAIL,SETOR_ID,FILEIRA,NUMERO,OBSERVACAO)
	VALUES('marcelo.rogerio@all-logistica.com', 8,10,100,'SETOR T001-10-100');
	

INSERT INTO LUGAR(USUARIO_EMAIL,SETOR_ID,FILEIRA,NUMERO,OBSERVACAO)
	VALUES('marcelo.rogerio@all-logistica.com', 1,6,5,'SETOR F001-6-5');
	
INSERT INTO LUGAR(USUARIO_EMAIL,SETOR_ID,FILEIRA,NUMERO,OBSERVACAO)
	VALUES('marcelo.rogerio@all-logistica.com', 7,7,15,'SETOR G001-7-15');

INSERT INTO LUGAR(USUARIO_EMAIL,SETOR_ID,FILEIRA,NUMERO,OBSERVACAO)
	VALUES('marcelo.rogerio@all-logistica.com', 7,7,20,'SETOR G001-7-20');
  





